### ISSUE TITLE
Sidebar links has relative routing

### ISSUE THREAD

**Issue by akovardakov** [best-doctor/ke#28]

**Comment by mcproger** [comment]
@akovardakov hello! Could you explain pls what do you mean here?

**Comment by akovardakov** [comment]
Sidebar link now has route `${name}`. react-router history.push in this case does a relative routing, e.g.:
location = '/appeals', route = 'patients', result = '/patients'
BUT
location = '/appeals/', route = 'patients', result = '/appeals/patients'
To prevent this we must prefix route with slash to make route absolute

**Comment by akovardakov** [comment]
Also in my pull request I added Redirect to trailing slash for list view, as basically it is a directory of items
